In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']


In [3]:

reviews

['nice food',
 'amazing restaurant',
 'too good',
 'just loved it!',
 'will go again',
 'horrible food',
 'never go there',
 'poor service',
 'poor quality',
 'needs improvement']

In [4]:
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
sentiment


array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [6]:
one_hot("amazing restaurant",75)


[62, 74]

In [7]:
vocab_size=75

In [8]:
encoded_views=[one_hot(d,vocab_size) for d in reviews]

In [9]:
encoded_views

[[54, 9],
 [62, 74],
 [37, 72],
 [38, 42, 58],
 [24, 65, 29],
 [5, 9],
 [54, 65, 73],
 [36, 60],
 [36, 55],
 [15, 56]]

In [10]:
max_length = 3
padded_reviews = pad_sequences(encoded_views, maxlen=max_length, padding='post')
print(padded_reviews)

[[54  9  0]
 [62 74  0]
 [37 72  0]
 [38 42 58]
 [24 65 29]
 [ 5  9  0]
 [54 65 73]
 [36 60  0]
 [36 55  0]
 [15 56  0]]


In [11]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='tanh'))

In [12]:
X = padded_reviews
y = sentiment

In [13]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              300       
                                                                 
 flatten (Flatten)           (None, 12)                0         
                                                                 
 dense (Dense)               (None, 1)                 13        
                                                                 
Total params: 313
Trainable params: 313
Non-trainable params: 0
_________________________________________________________________
None


In [14]:
model.fit(X,y,epochs=30)

Epoch 1/30
1/1 [==============================] - 0s 335ms/step - loss: 5.5293 - accuracy: 0.5000
Epoch 2/30
1/1 [==============================] - 0s 15ms/step - loss: 5.4523 - accuracy: 0.5000
Epoch 3/30
1/1 [==============================] - 0s 0s/step - loss: 5.4014 - accuracy: 0.5000
Epoch 4/30
1/1 [==============================] - 0s 5ms/step - loss: 5.3630 - accuracy: 0.5000
Epoch 5/30
1/1 [==============================] - 0s 5ms/step - loss: 5.3320 - accuracy: 0.5000
Epoch 6/30
1/1 [==============================] - 0s 3ms/step - loss: 5.3061 - accuracy: 0.5000
Epoch 7/30
1/1 [==============================] - 0s 4ms/step - loss: 5.2841 - accuracy: 0.5000
Epoch 8/30
1/1 [==============================] - 0s 3ms/step - loss: 5.2649 - accuracy: 0.5000
Epoch 9/30
1/1 [==============================] - 0s 3ms/step - loss: 5.2479 - accuracy: 0.5000
Epoch 10/30
1/1 [==============================] - 0s 4ms/step - loss: 5.2327 - accuracy: 0.5000
Epoch 11/30
1/1 [====================

In [15]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              300       
                                                                 
 flatten (Flatten)           (None, 12)                0         
                                                                 
 dense (Dense)               (None, 1)                 13        
                                                                 
Total params: 313
Trainable params: 313
Non-trainable params: 0
_________________________________________________________________


In [16]:
model.evaluate(X,y)

1/1 [==============================] - 0s 99ms/step - loss: 5.0755 - accuracy: 0.5000


[5.07546329498291, 0.5]

In [17]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)


75

In [18]:
weights[74]

array([-0.02349632,  0.0132453 ,  0.01194156, -0.0158842 ], dtype=float32)

In [19]:
weights[37]

array([ 0.01745275, -0.02478452, -0.02008945,  0.04160753], dtype=float32)

In [20]:
weights[11]

array([ 0.01954149, -0.01334568,  0.03727639, -0.02344668], dtype=float32)

In [21]:
weights[36]

array([ 0.02168914,  0.0351262 ,  0.04486316, -0.04225928], dtype=float32)